### ISSUE TITLE
Gemini support

### ISSUE THREAD

**Issue by waweic** [mdom/tazgopher#3]
Hi, I just found this repo (I tried to access gopher://taz.de during the outage of https://taz.de)

There is a relatively new protcol ([Gemini](https://gemini.circumlunar.space)) that tries to address the shortcomings of Gopher without becoming overly bloated like todays web. I think it's really promising and was wondering whether you would be interested in also making the taz available over it.

**Comment by mdom** [comment]
On Fri, Dec 31, 2021 at 07:20:43AM -0800, waweic wrote:
> There is a relatively new protcol
> ([Gemini](https://gemini.circumlunar.space)) that tries to address the
> shortcomings of Gopher without becoming overly bloated like todays
> web. I think it's really promising and was wondering whether you would
> be interested in also making the taz available over it.

Okay, i just deployed a initial version of our gemini port. Maybe you
could test it at gemini://taz.de?

Best regards, Mario

**Comment by waweic** [comment]
Hi Mario, it's great!
It works really really well!
I will definitely be using it a lot. I will post about it on Mastodon, others will probably like it as much as I do

**Comment by parimalsatyal** [comment]
Thank you! This is invaluable.
